version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: System.IO.Abstractions
    versions:
    - 13.2.10
    - 13.2.11
    - 13.2.15
    - 13.2.17
    - 13.2.20
    - 13.2.23
    - 13.2.24
    - 13.2.25
    - 13.2.28
    - 13.2.9
  - dependency-name: Google.Apis.Sheets.v4
    versions:
    - 1.49.0.2175
    - 1.50.0.2175
    - 1.50.0.2231
    - 1.50.0.2245
    - 1.51.0.2259
    - 1.51.0.2266
  - dependency-name: System.IO.Abstractions.TestingHelpers
    versions:
    - 13.2.10
    - 13.2.11
    - 13.2.15
    - 13.2.17
    - 13.2.20
    - 13.2.23
    - 13.2.24
    - 13.2.25
    - 13.2.28
    - 13.2.9
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: Bogus
    versions:
    - 32.0.2
    - 32.1.1
    - 33.0.1
